from __future__ import annotations

import sys
import os
import html
from pathlib import Path

import pandas as pd
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))


def load_local_env(env_path: Path) -> None:
    if not env_path.exists():
        return

    for line in env_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


load_local_env(PROJECT_ROOT / ".env")

from telemetry_dashboard.analysis import analyze_flight
from telemetry_dashboard.llm_summary import build_insight
from telemetry_dashboard.parser import parse_bin_log
from telemetry_dashboard.visualization import build_projection_figures, build_trajectory_figure

st.set_page_config(
    page_title="Telemetry Flight Analyzer",
    page_icon=":airplane:",
    layout="wide",
)

st.markdown(
    """
    <style>
    .ai-panel {
        border: 1px solid rgba(56, 189, 248, 0.35);
        background: linear-gradient(180deg, rgba(8, 47, 73, 0.28), rgba(15, 23, 42, 0.18));
        border-radius: 16px;
        padding: 1rem 1.1rem;
        margin: 1rem 0 1.25rem 0;
    }
    .ai-badge {
        display: inline-block;
        padding: 0.2rem 0.55rem;
        border-radius: 999px;
        font-size: 0.78rem;
        font-weight: 700;
        letter-spacing: 0.03em;
        color: #e0f2fe;
        background: rgba(14, 165, 233, 0.22);
        border: 1px solid rgba(56, 189, 248, 0.4);
        margin-bottom: 0.75rem;
    }
    .ai-title {
        font-size: 1.15rem;
        font-weight: 700;
        margin: 0 0 0.35rem 0;
    }
    .ai-subtitle {
        color: #cbd5e1;
        font-size: 0.92rem;
        margin-bottom: 0.9rem;
    }
    .ai-section {
        border-top: 1px solid rgba(148, 163, 184, 0.16);
        padding-top: 0.75rem;
        margin-top: 0.75rem;
    }
    .ai-section-title {
        font-size: 0.95rem;
        font-weight: 700;
        color: #f8fafc;
        margin-bottom: 0.28rem;
    }
    .ai-section-body {
        color: #e2e8f0;
        line-height: 1.55;
        font-size: 0.95rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


def load_uploaded_file(uploaded_file) -> Path:
    uploads_dir = PROJECT_ROOT / ".uploads"
    uploads_dir.mkdir(exist_ok=True)

    target_path = uploads_dir / uploaded_file.name
    target_path.write_bytes(uploaded_file.getbuffer())
    return target_path


def metrics_table(metrics: dict[str, float | str]) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"Metric": key.replace("_", " ").title(), "Value": value}
            for key, value in metrics.items()
        ]
    )


def render_ai_panel(text: str) -> None:
    sections: list[str] = []
    current_title: str | None = None
    current_body: list[str] = []

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("### "):
            if current_title is not None:
                sections.append(
                    f'<div class="ai-section"><div class="ai-section-title">{html.escape(current_title)}</div>'
                    f'<div class="ai-section-body">{" ".join(html.escape(part) for part in current_body)}</div></div>'
                )
            current_title = line[4:].strip()
            current_body = []
        else:
            current_body.append(line)

    if current_title is not None:
        sections.append(
            f'<div class="ai-section"><div class="ai-section-title">{html.escape(current_title)}</div>'
            f'<div class="ai-section-body">{" ".join(html.escape(part) for part in current_body)}</div></div>'
        )
    elif text.strip():
        sections.append(f'<div class="ai-section-body">{html.escape(text.strip())}</div>')

    st.markdown(
        f"""
        <div class="ai-panel">
            <div class="ai-badge">AI-GENERATED FLIGHT CONCLUSION</div>
            <div class="ai-title">Automated LLM assessment</div>
            <div class="ai-subtitle">
                This block is generated by the AI assistant from telemetry metrics and is intended
                as an interpretive conclusion, not just raw flight data.
            </div>
            {''.join(sections)}
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_report(log_path: Path) -> None:
    parsed = parse_bin_log(log_path)
    report = analyze_flight(parsed)

    st.subheader(f"Log: {log_path.name}")
    left, middle, right = st.columns(3)
    left.metric("Duration", f"{report.metrics.total_duration_s:.2f} s")
    middle.metric("Distance", f"{report.metrics.total_distance_m:.2f} m")
    right.metric("Max Altitude Gain", f"{report.metrics.max_altitude_gain_m:.2f} m")

    stat_left, stat_mid, stat_right = st.columns(3)
    stat_left.metric(
        "Max Horizontal Speed",
        f"{report.metrics.max_horizontal_speed_m_s:.2f} m/s",
    )
    stat_mid.metric(
        "Max Vertical Speed",
        f"{report.metrics.max_vertical_speed_m_s:.2f} m/s",
    )
    stat_right.metric(
        "Max Acceleration",
        f"{report.metrics.max_acceleration_m_s2:.2f} m/s^2",
    )

    st.caption(
        "The dashboard still integrates IMU accelerations with the trapezoidal rule, "
        "but the headline speed metrics are taken from GPS because pure IMU integration "
        "accumulates drift."
    )

    chart_col, info_col = st.columns([2, 1])
    with chart_col:
        st.markdown("### 3D ENU Trajectory")
        st.caption(
            "Interactive 3D trajectory in local ENU coordinates with three explicit axes: X = North, Y = East, Z = Height. The path is dynamically colored by time progression."
        )
        st.plotly_chart(build_trajectory_figure(report.enriched_samples), use_container_width=True)
    with info_col:
        st.markdown("### Sensor metadata")
        st.dataframe(
            pd.DataFrame(
                [
                    {
                        "Sensor": "GPS",
                        "Rows": parsed.metadata.gps_rows,
                        "Sampling frequency (Hz)": round(parsed.metadata.gps_frequency_hz, 3),
                        "Units": ", ".join(
                            f"{key}={value}" for key, value in parsed.metadata.gps_units.items()
                        ),
                    },
                    {
                        "Sensor": "IMU",
                        "Rows": parsed.metadata.imu_rows,
                        "Sampling frequency (Hz)": round(parsed.metadata.imu_frequency_hz, 3),
                        "Units": ", ".join(
                            f"{key}={value}" for key, value in parsed.metadata.imu_units.items()
                        ),
                    },
                ]
            ),
            use_container_width=True,
            hide_index=True,
        )
        st.markdown("### Speed cross-check")
        st.dataframe(
            pd.DataFrame(
                [
                    {
                        "Source": "GPS",
                        "Max horizontal speed (m/s)": report.metrics.max_horizontal_speed_m_s,
                        "Max vertical speed (m/s)": report.metrics.max_vertical_speed_m_s,
                    },
                    {
                        "Source": "IMU + trapezoidal integration",
                        "Max horizontal speed (m/s)": report.metrics.max_horizontal_speed_imu_m_s,
                        "Max vertical speed (m/s)": report.metrics.max_vertical_speed_imu_m_s,
                    },
                ]
            ),
            use_container_width=True,
            hide_index=True,
        )

    st.markdown("### Additional 2D Projections")
    st.caption("These 2D charts are supplementary views; the main trajectory panel above remains the primary 3D ENU visualization.")
    top_view, altitude_profile = build_projection_figures(report.enriched_samples)
    projection_left, projection_right = st.columns(2)
    with projection_left:
        st.plotly_chart(top_view, use_container_width=True)
    with projection_right:
        st.plotly_chart(altitude_profile, use_container_width=True)

    ai_text = build_insight(report)
    render_ai_panel(ai_text)

    st.markdown("### Summary table")
    st.dataframe(metrics_table(report.metrics.as_dict()), use_container_width=True, hide_index=True)

    st.markdown("### Sample preview")
    st.dataframe(report.enriched_samples.head(50), use_container_width=True)


def main() -> None:
    st.title("ArduPilot Telemetry Analyzer")
    st.write(
        "Upload an ArduPilot `.BIN` log or pick one of the bundled samples to parse telemetry, "
        "compute mission metrics, and inspect the 3D ENU trajectory."
    )

    bundled_logs: list[Path] = []
    for candidate_dir in (PROJECT_ROOT / "bin", PROJECT_ROOT / ".uploads"):
        if candidate_dir.exists():
            bundled_logs.extend(sorted(candidate_dir.glob("*.BIN")))

    deduped_logs: dict[str, Path] = {}
    for path in bundled_logs:
        deduped_logs.setdefault(path.name, path)
    bundled_logs = list(deduped_logs.values())

    with st.sidebar:
        st.header("Input")
        uploaded_file = st.file_uploader("Upload `.BIN` log", type=["bin", "BIN"])
        selected_sample = st.selectbox(
            "Or choose a bundled sample",
            options=["None", *[path.name for path in bundled_logs]],
        )
        st.caption(
            "The dashboard parses GPS, IMU, and ATT messages, estimates sampling rates, "
            "converts WGS-84 coordinates to ENU, and integrates accelerations with the trapezoidal rule."
        )

    if uploaded_file is not None:
        render_report(load_uploaded_file(uploaded_file))
        return

    if selected_sample != "None":
        render_report(next(path for path in bundled_logs if path.name == selected_sample))
        return

    st.info("Select one of the bundled flight logs or upload your own `.BIN` file to begin.")


if __name__ == "__main__":
    main()
